stages:
  - test
  - build
  - release

unit-tests:
  stage: test
  image: rust:latest
  script:
    - cargo install cargo-tarpaulin
    - cd backend
    - cargo tarpaulin --include-files *domain*
  coverage: '/^\d+.\d+% coverage/'

building:
  stage: build
  image: docker:27.5.1-cli-alpine3.21⁠
  script:
    - docker compose build --no-cache

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
    - docker compose build --no-cache
    - docker compose save -o rusty-minesweeper.tar rusty-minesweeper-backend rusty-minesweeper-frontend mongo
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
