image: rust:latest

stages:
  - test
  - build

unit-tests:
  stage: test
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin
    - echo $COVERAGE
  coverage: '/^\d+\.\d+/% coverage,*/'

building:
  stage: build
  script:
    - cargo build
    - echo $COVERAGE
