image: rust:latest

stages:
  - test
  - build

unit-tests:
  stage: test
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin
  coverage: '/^[0-9]\{2,3\}\.[0-9]\{2\}\% coverage/'

building:
  stage: build
  script:
    - cargo build
