bin = [
  { name = "main", path = "src/main.rs" },
]

[package]
name = "rusty-minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.6"
rand = "0.8"
rand_chacha = "0.3"
itertools = "0.14"
